### ISSUE TITLE
Feature idea: Make log entries able to be copied

### ISSUE THREAD

**Issue by deckerweb** [Section214/pressmatic-addon-logs#1]
Hi there,
thanks for this great add-on - so far works like a charm! Really useful!

Just wanted to suggest a feature idea: to make each entry/line in a log able to be copied by marking with the mouse. So I could copy just a PHP error for example. Could be helpful. Don't know if this would be possible with this kind of app/ add-on, though.

Thanks in advance, and keep up the good work! :-)

**Comment by evertiro** [comment]
Your wish is my command! Grab release 1.0.1. (btw, I haven't even announced this yet... how'd you stumble on it?)

**Comment by evertiro** [comment]
@deckerweb Correction, grab 1.0.2. Much stabler!

**Comment by deckerweb** [comment]
Hi,
thanks a lot, just perfect! :)

I saw it on github.com start page feed - since I am following you :)
I am new to Pressmatic and loving it, so your add-on is a welcomed addition - thanks for creating it!
